---
name: cmpsc-302-spring-2019-lab4
break: true
indent: 4
---
# --> check the source code for various characteristics
# note that without an "--exact" the check is an "at least"
src/www/:
    index.html:
        --fragment "<title>Share Your Travels</title>" --count 1 --exact
        --fragment "<h1>Share Your Travels</h1>" --count 1 --exact
        --fragment "<h3>Photograph Reviews</h3>" --count 1 --exact
        --fragment "<h3>Travel Tips</h3>" --count 1 --exact
        --fragment "<p>" --count 15
        --fragment "<time>" --count 5
        --fragment "<blockquote>" --count 5
        --fragment "<a href" --count 3
        --fragment "_blank" --count 3
        --fragment "<html>" --count 1 --exact
        --fragment "<head>" --count 1 --exact
        --fragment "<body>" --count 1 --exact
        --fragment "<ol>" --count 1 --exact
        --fragment "<li>" --count 3 --exact
        --fragment "site.css" --count 1 --exact
        --fragment "emoji.css" --count 1 --exact
        --fragment "<tr>" --count 5 --exact
        --fragment "TODO" --count 0 --exact
# --> check the technical writing
# mdl is a Markdown linting tool
# proselint checks writing for common mistakes
writing/reflection.md:
    mdl
    proselint
    --paragraphs 5
    --words 100
# --> check the submission image exists
images/travels_submission.png:
    --exists
src/www/css:
    site.css:
        --fragment "font-family" --count 2
        --fragment "0 1pt 1pt 0" --count 1
src/www/css:
    table.css:
        --fragment "nth-child" --count 2
        --fragment "hover" --count 1
        --fragment "600px" --count 1
        --fragment "tr" --count 5
        --fragment "td" --count 5
        --fragment "th" --count 6
# --> check the number of commits beyond a threshold
--commits 19
# --> check that the linter executes and produces 0 lines of output
--command "htmlhint src/www/index.html" --executes
--command "htmlhint src/www/index.html" --count 1 --exact
--command "htmlhint src/www/index.html" --fragment "no errors found" --count 1 --exact
